In [1]:
import pandas as pd
import numpy as np

In [2]:
dados=pd.read_csv('weight_change_dataset.csv')
display(dados.head())
estatistica=dados.describe()
display(estatistica)
df_copia=dados.copy() #BOAS PRÁTICAS: sempre inicie com uma cópia do dataset original para as primeiras manipulações/edições de dados
display(df_copia)

,Participant ID,Age,Gender,Current Weight (lbs),BMR (Calories),Daily Calories Consumed,Daily Caloric Surplus/Deficit,Weight Change (lbs),Duration (weeks),Physical Activity Level,Sleep Quality,Stress Level,Final Weight (lbs)
0,1,56,M,228.4,3102.3,3916.0,813.7,0.2,1,Sedentary,Excellent,6,228.6
1,2,46,F,165.4,2275.5,3823.0,1547.5,2.4,6,Very Active,Excellent,6,167.8
2,3,32,F,142.8,2119.4,2785.4,666.0,1.4,7,Sedentary,Good,3,144.2
3,4,25,F,145.5,2181.3,2587.3,406.0,0.8,8,Sedentary,Fair,2,146.3
4,5,38,M,155.5,2463.8,3312.8,849.0,2.0,10,Lightly Active,Good,1,157.5

,Participant ID,Age,Current Weight (lbs),BMR (Calories),Daily Calories Consumed,Daily Caloric Surplus/Deficit,Weight Change (lbs),Duration (weeks),Stress Level,Final Weight (lbs)
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,37.910000,171.533000,2518.206000,3518.292000,1000.091000,-2.779817,6.920000,4.810000,168.750000
std,29.011492,12.219454,30.333856,364.431221,513.313097,371.560827,7.443719,3.515277,2.576879,30.588004
min,1.000000,18.000000,100.000000,1566.500000,2030.900000,82.500000,-35.678115,1.000000,1.000000,98.200000
25%,25.750000,26.750000,153.650000,2255.050000,3233.300000,766.950000,-5.012312,4.000000,2.750000,149.550000
50%,50.500000,38.000000,172.150000,2519.500000,3636.050000,1013.100000,0.100000,7.000000,5.000000,169.800000
75%,75.250000,46.250000,192.475000,2805.975000,4000.000000,1253.325000,1.850000,10.000000,7.000000,188.300000
max,100.000000,59.000000,238.200000,3390.800000,4000.000000,1922.500000,5.000000,12.000000,9.000000,232.500000

,Participant ID,Age,Gender,Current Weight (lbs),BMR (Calories),Daily Calories Consumed,Daily Caloric Surplus/Deficit,Weight Change (lbs),Duration (weeks),Physical Activity Level,Sleep Quality,Stress Level,Final Weight (lbs)
0,1,56,M,228.4,3102.3,3916.0,813.7,0.20000,1,Sedentary,Excellent,6,228.6
1,2,46,F,165.4,2275.5,3823.0,1547.5,2.40000,6,Very Active,Excellent,6,167.8
2,3,32,F,142.8,2119.4,2785.4,666.0,1.40000,7,Sedentary,Good,3,144.2
3,4,25,F,145.5,2181.3,2587.3,406.0,0.80000,8,Sedentary,Fair,2,146.3
4,5,38,M,155.5,2463.8,3312.8,849.0,2.00000,10,Lightly Active,Good,1,157.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,59,M,181.9,2622.8,3656.2,1033.4,0.60000,2,Lightly Active,Excellent,3,182.5
96,97,56,F,116.5,1736.5,2756.5,1020.0,-8.92309,12,Moderately Active,Good,9,107.6
97,98,58,F,162.7,2188.6,3344.3,1155.8,3.60000,12,Lightly Active,Fair,7,166.3
98,99,45,M,179.8,2671.9,4000.0,1328.1,2.00000,5,Moderately Active,Fair,5,181.8
99,100,24,M,185.2,2830.7,4000.0,1169.3,2.70000,9,Very Active,Fair,7,187.9

Consultas:

In [3]:
#Selecionando a informação por índices (linhas e/ou colunas específicas):
df_loc2=df_copia.iloc[:2,:4]
display(df_loc2)

   Participant ID  Age Gender  Current Weight (lbs)
0               1   56      M                 228.4
1               2   46      F                 165.4

In [4]:
#Selecionando todos os Níveis de Qualidade de Sono que sejam 'Excellent':
df_loc=df_copia.loc[df_copia['Sleep Quality']=='Excellent']
display(df_loc)

,Participant ID,Age,Gender,Current Weight (lbs),BMR (Calories),Daily Calories Consumed,Daily Caloric Surplus/Deficit,Weight Change (lbs),Duration (weeks),Physical Activity Level,Sleep Quality,Stress Level,Final Weight (lbs)
0,1,56,M,228.4,3102.3,3916.0,813.7,0.200000,1,Sedentary,Excellent,6,228.6
1,2,46,F,165.4,2275.5,3823.0,1547.5,2.400000,6,Very Active,Excellent,6,167.8
9,10,28,F,169.2,2403.3,2485.8,82.5,0.000000,2,Sedentary,Excellent,7,169.2
11,12,53,M,138.4,2217.4,3604.9,1387.6,2.000000,5,Moderately Active,Excellent,5,140.4
12,13,57,F,147.3,2039.0,2803.1,764.1,1.200000,6,Sedentary,Excellent,2,148.5
21,22,38,F,214.4,2805.6,3274.1,468.5,0.400000,4,Sedentary,Excellent,3,214.8
27,28,59,M,151.4,2318.0,3877.8,1559.8,-3.678736,6,Very Active,Excellent,8,147.7
34,35,38,F,228.0,2941.7,4000.0,1058.3,0.900000,3,Moderately Active,Excellent,1,228.9
39,40,42,M,141.5,2303.3,3352.3,1049.0,3.600000,12,Lightly Active,Excellent,2,145.1
59,60,35,M,138.1,2304.3,3424.8,1120.5,1.500000,5,Lightly Active,Excellent,5,139.6
62,63,27,F,197.6,2692.7,4000.0,1307.3,2.000000,5,Very Active,Excellent,6,199.6
86,87,25,M,165.8,2631.5,3536.0,904.5,1.500000,5,Lightly Active,Excellent,2,167.3
90,91,25,M,195.5,2928.8,3758.6,829.8,0.800000,4,Lightly Active,Excellent,3,196.3
91,92,52,F,181.8,2409.8,2640.7,230.9,1.000000,10,Lightly Active,Excellent,7,182.8
93,94,50,M,122.9,2077.5,4000.0,1922.5,5.000000,10,Very Active,Excellent,6,127.9
95,96,59,M,181.9,2622.8,3656.2,1033.4,0.600000,2,Lightly Active,Excellent,3,182.5

In [ ]:
#Selecionando A Partir de Filtros com Teste Lógico:
df_query=df_copia.query('Age<40')
display(df_query)

ATIVIDADE 1: (AULA)
A partir do dataset trabalhado nesta aula, trace 3 perfis e os demonstre pelo display:

Perfil 1: Pessoas sedentárias com dietas alimentares de até 2200 calorias; Perfil 2: Pessoas acima de 50 anos com hábitos muito bons de atividade física; Perfil 3: Pessoas com menos de 20 anos que participaram dos estudos nutricionais por mais de 1 mês.

ATIVIDADE 2: (GITHUB)
Replique os processos de leitura, cópia e consultas exercitados em aula utilizando um dataset livre pesquisado por você (dê preferência a arquivos .csv, .xlsx ou .json).